[scan]
# 要扫描的文件夹（支持环境变量）
directory = %USERPROFILE%\Desktop\

# 文件匹配模式 —— 在这里定义你想清理的任意文件类型（英文逗号分隔）
patterns = *.ppt, *.pptx

# 是否扫描子目录？true 或 false
recursive = false

[time]
# 天数：设为 0 表示不限制该条件
creation_days = 3      # 创建时间早于 3 天的文件将被移动
access_days = 2        # 最后访问时间早于 2 天的文件将被移动
