[scan]
# Folder to scan (supports environment variables)
directory = %USERPROFILE%\Desktop\

# File patterns – define ANY file types you want to clean (comma‑separated)
patterns = *.ppt, *.pptx

# Scan sub‑directories? true or false
recursive = false

[time]
# Days: 0 means "no restriction"
creation_days = 3      # Move files older than 3 days (created)
access_days = 2        # Move files older than 2 days (last opened)
